services:
  - type: web
    name: ib-hex-bot
    runtime: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: NODE_VERSION
        value: 18
    plan: free
